### PR TITLE
Cleaned up the UI

### PR DESCRIPTION
**Pull request by suchk**

### CODE REVIEW

**Comment by ddh** [comment]
I took a look, the UI elements on the screen stand out better. Could we make the score font size larger?

**Comment by suchk** [comment]
Totally. How does the new size look?

**Comment by ddh** [comment]
Better! More readable. Yellow is goshdarn hard to see but I think we can tackle that later, unless you got an idea for a fix! I was thinking we put a badge/icon/player-portrait behind each score to make the scores pop-out and also eliminate yellow from clashing with the game background.

**Comment by suchk** [comment]
I changed it to a darker shade (closer to gold). Definitely more readable now I think. Does it still need the badges?

**Comment by ddh** [comment]
Yeah, I think that color is better than the previous! As for badges, the numbers would pop out with a some sort of graphic as backing but really that's just polish. This looks great as is

**Pull request merged**
